### ISSUE TITLE
Crash on startup - Fabric Server 1.16.5

### ISSUE THREAD

**Issue by JoakoLP** [EwyBoy/CHA-S#11]
My server have this mods:
![image](https://user-images.githubusercontent.com/82276442/138101615-f64e6fa0-c469-4ec0-b20a-8f181e592482.png)
And if I try to startup with CHAS, it crashes. But if I delete the mod, it runs

This is the log:
[https://pastebin.com/vzGyEJd6](url)

**Comment by EwyBoy** [comment]
Okey, I will look into it

**Comment by EwyBoy** [comment]
Done several different tests and can confirm this mod is not causing any server crashes on its own.
The problem is with on of the other mods that you are using causing the crash in this mod.

This mod has no code at all and is really just a glorified resource pack, so there is actually no way this mod could cause any crashes on its own without some other mods messing with recipes or datapacks with their mixins.

I would suggest looking through the crashlogs and check if some other mods are running some mixins on the crafting recipes or datapacks causing the crash.

![image](https://user-images.githubusercontent.com/5883716/138108886-71de455e-2f06-40c4-b710-c6fa5d6d1036.png)
